FROM java

RUN echo " start manage_cms ..."

MAINTAINER jiangkang

WORKDIR /

CMD ["java","version"]

COPY eureka_server/target/xc-service-manage-cms.jar main.jar

ENTRYPOINT ["java", "-jar", "main.jar"]
