FROM java

RUN echo " start eureka_server ..."

MAINTAINER jiangkang

WORKDIR /

CMD ["java","version"]

COPY xc_eureka_server/target/xc_eureka_server.jar main.jar

ENTRYPOINT ["java", "-jar", "main.jar"]
